<?php
$_SERVER['REQUEST_METHOD']='CLI';
require_once __DIR__.'/../api/lib/certificate_service.php';

$inspection=['id'=>990013,'inspection_date'=>'2026-07-16','next_due_date'=>'2027-01-16','location'=>'Riverside Equipment Yard, Port Harcourt','client_name'=>'Riverside Fabrication Services','client_address'=>'Industrial Layout, Port Harcourt','equipment_name'=>'Hook Register','asset_code'=>'RFS-HK','inspector_name'=>'Qualified Inspection Officer','inspector_qualification'=>'LEEA, ASNT II'];
$values=['report_date'=>'2026-07-16','colour_code'=>'BLUE','standard'=>'BS EN 13889','inspector_name_snapshot'=>'Qualified Inspection Officer','inspector_qualification_snapshot'=>'LEEA, ASNT II','authenticator_name'=>'Certification Reviewer','authenticator_qualification'=>'LEEA LMM','defect_observation_sheet_attached'=>'No'];
$rows=[];foreach($values as $key=>$value)$rows[]=['field_key'=>$key,'label'=>ucwords(str_replace('_',' ',$key)),'is_required'=>in_array($key,['colour_code','standard','defect_observation_sheet_attached'],true)?1:0,'value_text'=>$value];
$base=['identification_number'=>'RFS/HK/001','description'=>'Shouldered Hook','working_load_limit'=>'2 TONNES','last_thorough_examination_date'=>'2026-01-15','manufacturer'=>'Crosby','next_thorough_examination_date'=>'2027-01-16','reason_for_examination_code'=>'B','test_details'=>'Visual Examination','status_code'=>'ND','safe_to_use'=>'Yes'];
function hook_cells(array $rows):array{$cells=[];foreach($rows as $index=>$row)foreach($row as $key=>$value)$cells[]=['section_key'=>'hook_items','row_index'=>$index,'column_key'=>$key,'value_text'=>$value];return $cells;}
$failed=0;$items=hook_cells([$base]);$ready=hook_readiness($inspection,$rows,$items,'JUVA/RFS/HOOK/001','2026-07-16','2027-01-16');if(!$ready['ready']){echo "HOOK READINESS: FAIL\n";print_r($ready);$failed++;}else echo "HOOK READINESS: PASS\n";
foreach(['A','B','C','D','E'] as $reason){$copy=$base;$copy['reason_for_examination_code']=$reason;if(!hook_readiness($inspection,$rows,hook_cells([$copy]),'JUVA/RFS/HOOK/001','2026-07-16','2027-01-16')['ready']){$failed++;echo "HOOK REASON $reason: FAIL\n";}}echo "HOOK REASON MATRIX: ".($failed?'CHECK':'PASS')."\n";
foreach(['ND','SDR','NF','OBS'] as $status)foreach(['Yes','No'] as $answer){$copy=$base;$copy['status_code']=$status;$copy['safe_to_use']=$answer;if(!hook_readiness($inspection,$rows,hook_cells([$copy]),'JUVA/RFS/HOOK/001','2026-07-16','2027-01-16')['ready']){$failed++;echo "HOOK STATUS $status / $answer: FAIL\n";}}
$tooMany=array_fill(0,7,$base);$overflow=hook_readiness($inspection,$rows,hook_cells($tooMany),'JUVA/RFS/HOOK/001','2026-07-16','2027-01-16');if(!isset($overflow['validation_errors']['hook_items'])){$failed++;echo "HOOK ROW LIMIT: FAIL\n";}else echo "HOOK ROW LIMIT: PASS\n";
$six=[];for($n=1;$n<=6;$n++){$row=$base;$row['serial_number']=(string)$n;$row['identification_number']='RFS/HK/'.str_pad((string)$n,3,'0',STR_PAD_LEFT);$six[]=$row;}
$audit=ensure_private_storage_dir('audit/hook/run-'.gmdate('Ymd-His'));$pdf=$audit.DIRECTORY_SEPARATOR.'non-aveon-hook.pdf';$payload=hook_payload($inspection,$rows,hook_cells($six),'JUVA/RFS/HOOK/001',1,'https://cert.juvaoil.com/verify/0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef','2026-07-16','2027-01-16');$payload['authentication']=['inspector_signature_path'=>null,'authenticator_signature_path'=>null];$payload['status']='VALID';hook_render_certificate_pdf($pdf,$payload);$bytes=(string)file_get_contents($pdf);if(!is_file($pdf)||filesize($pdf)<100000||strpos($bytes,'/MediaBox [0 0 842 595]')===false||strpos($bytes,'/Count 1')===false){$failed++;echo "HOOK LANDSCAPE PDF: FAIL\n";}else echo "HOOK LANDSCAPE PDF: PASS\n";
function hook_extract_jpeg(string $pdf,string $jpg):bool{$data=file_get_contents($pdf);$object=strpos($data,'5 0 obj');$start=$object===false?false:strpos($data,"stream\n",$object);if($start===false)return false;$start+=7;$end=strpos($data,"\nendstream",$start);return $end!==false&&file_put_contents($jpg,substr($data,$start,$end-$start))!==false;}
$tmp=$audit.DIRECTORY_SEPARATOR.'generated.jpg';$reference='C:/AppServ/www/FARM ALEX/REDUCED IMAGES/HOOK.jpg';if(hook_extract_jpeg($pdf,$tmp)&&is_file($reference)){$gen=imagecreatefromjpeg($tmp);$ref=imagecreatefromjpeg($reference);$w=1024;$h=724;$gs=imagecreatetruecolor($w,$h);$rs=imagecreatetruecolor($w,$h);imagecopyresampled($gs,$gen,0,0,0,0,$w,$h,imagesx($gen),imagesy($gen));imagecopyresampled($rs,$ref,0,0,0,0,$w,$h,imagesx($ref),imagesy($ref));$side=imagecreatetruecolor($w*2,$h);imagecopy($side,$rs,0,0,0,0,$w,$h);imagecopy($side,$gs,$w,0,0,0,$w,$h);imagepng($side,$audit.DIRECTORY_SEPARATOR.'side-by-side.png');$overlay=imagecreatetruecolor($w,$h);imagecopy($overlay,$rs,0,0,0,0,$w,$h);imagecopymerge($overlay,$gs,0,0,0,0,$w,$h,50);imagepng($overlay,$audit.DIRECTORY_SEPARATOR.'overlay-50-percent.png');$diff=imagecreatetruecolor($w,$h);for($y=0;$y<$h;$y++)for($x=0;$x<$w;$x++){$a=imagecolorat($rs,$x,$y);$b=imagecolorat($gs,$x,$y);$r=abs((($a>>16)&255)-(($b>>16)&255));$g=abs((($a>>8)&255)-(($b>>8)&255));$bl=abs(($a&255)-($b&255));imagesetpixel($diff,$x,$y,(($r<<16)|($g<<8)|$bl));}imagepng($diff,$audit.DIRECTORY_SEPARATOR.'pixel-difference.png');foreach([$gen,$ref,$gs,$rs,$side,$overlay,$diff] as $image)imagedestroy($image);@unlink($tmp);echo "HOOK VISUAL ARTIFACTS: PASS\n";}else{$failed++;echo "HOOK VISUAL ARTIFACTS: FAIL\n";}
echo "HOOK AUDIT DIR: $audit\n";exit($failed?1:0);
