<?php
declare(strict_types=1);
require_once __DIR__.'/../api/lib/certificate_service.php';
require_once __DIR__.'/../api/certificates/mappers/shackles_mapper.php';
require_once __DIR__.'/../api/certificates/templates/shackles.php';
$inspection=['id'=>999,'inspection_date'=>'2026-08-11','next_due_date'=>'2027-02-11','location'=>'Port Harcourt','client_name'=>'TEST CLIENT','client_address'=>'Test Address','equipment_name'=>'Test Bow Shackle','asset_code'=>'SHK-001','inspector_name'=>'Test Inspector','inspector_qualification'=>'LEEA'];
$values=['client_address'=>'Test Address','inspection_location'=>'Port Harcourt','accessory_type'=>'Bow Shackle','size_marking'=>'25 mm','manufacturer'=>'Crosby','standard'=>'BS EN 13889','safe_working_load'=>'25 TONNES','pin_condition'=>'pass','body_distortion_check'=>'pass','defect_observation_sheet_attached'=>'No'];
$rows=[];foreach($values as $key=>$value)$rows[]=['field_key'=>$key,'label'=>$key,'is_required'=>1,'value_text'=>$value];
$items=[['section_key'=>'shackles_items','row_index'=>0,'column_key'=>'serial_number','value_text'=>'SHK-001'],['section_key'=>'shackles_items','row_index'=>0,'column_key'=>'description','value_text'=>'Bow shackle'],['section_key'=>'shackles_items','row_index'=>0,'column_key'=>'swl_wll','value_text'=>'25 TONNES'],['section_key'=>'shackles_items','row_index'=>0,'column_key'=>'manufacturer','value_text'=>'Crosby'],['section_key'=>'shackles_items','row_index'=>0,'column_key'=>'status','value_text'=>'ND']];
$r=shackles_readiness($inspection,$rows,$items,'JUVA/TEST/SHK/001','2026-08-11','2027-02-11');if(!$r['ready']){echo "SHACKLES READINESS: FAIL\n";print_r($r);exit(1);}echo "SHACKLES READINESS: PASS\n";
$p=shackles_payload($inspection,$rows,$items,'JUVA/TEST/SHK/001',1,'https://cert.juvaoil.com/verify/test-token','2026-08-11','2027-02-11');$p['authentication']=['inspector_signature_path'=>null,'authenticator_signature_path'=>null];$dir=sys_get_temp_dir().'/juva-shackles-test';if(!is_dir($dir)&&!mkdir($dir,0775,true))exit(1);foreach(['VALID'=>'shackles-valid.pdf','EXPIRED'=>'shackles-expired.pdf'] as $status=>$name){$p['status']=$status;$pdf=$dir.'/'.$name;shackles_render_certificate_pdf($pdf,$p);if(!is_file($pdf)||filesize($pdf)<10000)exit(1);echo "SHACKLES $status LANDSCAPE PDF: PASS\n";}
