<?php
require_once __DIR__ . '/../mappers/hook_mapper.php';
require_once __DIR__ . '/landscape_pdf.php';

function hook_render_certificate_pdf(string $path, array $p): void
{
    $im=imagecreatetruecolor(2339,1654); imagefilledrectangle($im,0,0,2339,1654,certificate_color($im,'#FFFFFF'));
    $font=certificate_find_font(false); $bold=certificate_find_font(true)?:$font; $ink='#202020'; $line='#222222';
    $asset=dirname(__DIR__,3).'/public/assets/certificates/endless-round-webbing-sling';
    $fit=static function($im,string $v,int $x,int $y,int $w,int $h,int $size,?string $f,string $align='left') use($ink):void{ccu_draw_text_fit($im,$v,$x,$y,$w,$h,$size,$ink,$f,false,$align);};
    $cell=static function($im,int $x,int $y,int $w,int $h,string $v,int $size,?string $f,string $align='left') use($line,$fit):void{imagerectangle($im,$x,$y,$x+$w,$y+$h,certificate_color($im,$line));$fit($im,$v,$x+2,$y+2,$w-4,$h-4,$size,$f,$align);};
    $put=static function($im,string $file,int $x,int $y,int $w,int $h):void{if(!is_file($file))return;$bytes=@file_get_contents($file);$src=$bytes!==false?@imagecreatefromstring($bytes):false;if(!$src)return;$scale=min($w/imagesx($src),$h/imagesy($src));$dw=(int)round(imagesx($src)*$scale);$dh=(int)round(imagesy($src)*$scale);imagecopyresampled($im,$src,$x+(int)(($w-$dw)/2),$y+(int)(($h-$dh)/2),0,0,$dw,$dh,imagesx($src),imagesy($src));imagedestroy($src);};
    $tick=static function($im,int $x,int $y,int $w,int $h):void{$c=certificate_color($im,'#111111');imagesetthickness($im,4);imageline($im,$x+(int)($w*.25),$y+(int)($h*.55),$x+(int)($w*.43),$y+(int)($h*.72),$c);imageline($im,$x+(int)($w*.43),$y+(int)($h*.72),$x+(int)($w*.78),$y+(int)($h*.27),$c);imagesetthickness($im,1);};
    $rounded=static function($im,int $x1,int $y1,int $x2,int $y2,int $r) use($line):void{$c=certificate_color($im,$line);imageline($im,$x1+$r,$y1,$x2-$r,$y1,$c);imageline($im,$x1+$r,$y2,$x2-$r,$y2,$c);imageline($im,$x1,$y1+$r,$x1,$y2-$r,$c);imageline($im,$x2,$y1+$r,$x2,$y2-$r,$c);imagearc($im,$x1+$r,$y1+$r,$r*2,$r*2,180,270,$c);imagearc($im,$x2-$r,$y1+$r,$r*2,$r*2,270,360,$c);imagearc($im,$x1+$r,$y2-$r,$r*2,$r*2,90,180,$c);imagearc($im,$x2-$r,$y2-$r,$r*2,$r*2,0,90,$c);};
    $text=static function($im,string $v,int $x,int $y,int $s,?string $f,string $align='left') use($ink):void{certificate_draw_text($im,$v,$x,$y,$s,$ink,$f,$align);};

    $put($im,$asset.'/leea-logo.png',65,35,175,120); $put($im,dirname(__DIR__,3).'/public/logo.png',2070,35,205,120);
    $rounded($im,320,60,2015,155,18); $text($im,'JUVA-OIL SERVICES (NIG) LIMITED',1168,128,42,$bold,'center');
    $text($im,'CERTIFICATE OF THOROUGH EXAMINATION',1168,215,35,$bold,'center');
    foreach(["This report complies with the Lifting Equipment Engineers Association's technical requirements",'The Lifting Operations and Lifting Equipment Regulations 1998 SI NO.2307','The Supply of Machinery (Safety) Regulation 1992 SI NO.3073','The Provision and Use of Work Equipment Regulations 1998 SI NO.2306','Nigeria Factories Act CAP F1 LFN, 2004'] as $i=>$r)$text($im,$r,1168,258+($i*24),17,$font,'center');
    $status=strtoupper((string)($p['status']??'VALID')); $sc=$status==='REVOKED'?'#9B1C1C':($status==='EXPIRED'?'#8A5600':'#08775E'); imagerectangle($im,2070,180,2265,235,certificate_color($im,$sc));certificate_draw_text($im,$status,2167,218,22,$sc,$bold,'center');

    $x=60;$w=2219;$y=475;$fields=$p['fields'];
    $metaW=[430,500,430,400,459];$meta=["CERTIFICATE NO:\n".$p['certificate_number'],"DATE OF THOROUGH EXAMINATION:\n".hook_date((string)$p['examination_date']),"DATE OF REPORT:\n".hook_date((string)$p['report_date']),"COLOUR CODE:\n".strtoupper((string)($fields['colour_code']??'')),"STANDARD:\n".strtoupper((string)($fields['standard']??''))];$cx=$x;foreach($metaW as $i=>$cw){$cell($im,$cx,$y,$cw,72,$meta[$i],19,$i<3?$bold:$font,'center');$cx+=$cw;}$y+=72;
    $clientW=1050;$premW=545;$legendW=$w-$clientW-$premW;
    $cell($im,$x,$y,$clientW,105,"NAME AND ADDRESS OF EMPLOYER FOR WHOM THE THOROUGH EXAMINATION WAS MADE:\n".strtoupper((string)$p['client_name'])."\n".strtoupper((string)$p['client_address']),18,$font);
    $cell($im,$x+$clientW,$y,$premW,105,"ADDRESS OF PREMISES AT WHICH THE EXAMINATION WAS MADE:\n".strtoupper((string)$p['inspection_location']),18,$font,'center');
    $cell($im,$x+$clientW+$premW,$y,$legendW,105,"STATUS:\nND - NO DEFECT, SDR - SEE DEFECT REPORT\nNF - NOT FOUND, OBS - OBSERVATION",16,$font);$y+=105;

    $widths=[72,270,285,150,190,225,195,145,205,140,142];$headers=['S/N','IDENTIFICATION NUMBER','DESCRIPTION','WLL OR SWL','LAST THOROUGH EXAMINATION','MANUFACTURER','NEXT THOROUGH EXAMINATION','REASON CODE','DETAILS OF TEST','STATUS','SAFE TO USE'];$cx=$x;foreach($widths as $i=>$cw){$cell($im,$cx,$y,$cw,84,$headers[$i],15,$bold,'center');$cx+=$cw;}$y+=84;
    $items=$p['items'];$rowH=count($items)>4?60:72;foreach($items as $index=>$item){$values=[($item['serial_number']??'')!==''?$item['serial_number']:(string)($index+1),$item['identification_number']??'',$item['description']??'',$item['working_load_limit']??'',hook_date((string)($item['last_thorough_examination_date']??'')),$item['manufacturer']??'',hook_date((string)($item['next_thorough_examination_date']??'')),strtoupper((string)($item['reason_for_examination_code']??'')),$item['test_details']??'',strtoupper((string)($item['status_code']??'')),strtoupper((string)($item['safe_to_use']??''))];$cx=$x;foreach($widths as $i=>$cw){$cell($im,$cx,$y,$cw,$rowH,(string)$values[$i],$i===2?18:16,$i===2?$bold:$font,'center');$cx+=$cw;}$y+=$rowH;}
    $cell($im,$x,$y,$w,52,'REASON FOR EXAMINATION    INSTALLATION: A     6 MONTHLY: B     12 MONTHLY: C     WRITTEN SCHEME: D     EXCEPTIONAL CIRCUMSTANCE: E',17,$bold);$y+=70;
    $signW=(int)($w/2);$cell($im,$x,$y,$signW,130,"NAME & QUALIFICATIONS OF THE PERSON MAKING THIS REPORT:\n".strtoupper((string)$p['inspector_name'])."\n".strtoupper((string)$p['inspector_qualification'])."\nSIGNATURE:",18,$font);$cell($im,$x+$signW,$y,$w-$signW,130,"PERSON SIGNING OR AUTHENTICATING THIS REPORT:\n".strtoupper((string)$p['authenticator_name'])."\n".strtoupper((string)$p['authenticator_qualification'])."\nSIGNATURE:",18,$font);$auth=is_array($p['authentication']??null)?$p['authentication']:[];if(!empty($auth['inspector_signature_path']))$put($im,(string)$auth['inspector_signature_path'],$x+690,$y+70,180,50);if(!empty($auth['authenticator_signature_path']))$put($im,(string)$auth['authenticator_signature_path'],$x+$signW+690,$y+70,180,50);$y+=130;
    $labelW=470;$ynW=90;$markW=70;$cell($im,$x,$y,$labelW,52,'DEFECT / OBSERVATION SHEET ATTACHED?',17,$bold);$cell($im,$x+$labelW,$y,$ynW,52,'YES',17,$bold,'center');$cell($im,$x+$labelW+$ynW,$y,$markW,52,'',17,$font);$cell($im,$x+$labelW+$ynW+$markW,$y,$ynW,52,'NO',17,$bold,'center');$cell($im,$x+$labelW+($ynW*2)+$markW,$y,$markW,52,'',17,$font);$attached=strtolower((string)($fields['defect_observation_sheet_attached']??''));if($attached==='yes')$tick($im,$x+$labelW+$ynW,$y,$markW,52);if($attached==='no')$tick($im,$x+$labelW+($ynW*2)+$markW,$y,$markW,52);

    $footerY=$y+75;$put($im,$asset.'/bsi-logo.png',$x,$footerY,125,90);$put($im,$asset.'/leea-logo.png',$x+150,$footerY,115,90);$put($im,$asset.'/asnt-logo.png',$x+290,$footerY,150,90);
    $fit($im,strtoupper((string)$p['company']['name'])."\n".(string)$p['company']['operational']."\n".(string)$p['company']['phone'].' | '.(string)$p['company']['email'],$x+480,$footerY,1080,105,15,$font);
    if(class_exists('QRCode')){$qr=QRCode::getMinimumQRCode((string)$p['verification_url'],QR_ERROR_CORRECT_LEVEL_M);$n=(int)$qr->getModuleCount();$q=4;$m=4;$size=($n+8)*$m;$cardX=1680;$cardY=$footerY-12;$cardW=590;$cardH=215;imagefilledrectangle($im,$cardX,$cardY,$cardX+$cardW,$cardY+$cardH,certificate_color($im,'#FFFFFF'));imagerectangle($im,$cardX,$cardY,$cardX+$cardW,$cardY+$cardH,certificate_color($im,'#1F4B45'));$qx=$cardX+$cardW-$size-16;$qy=$cardY+12;imagefilledrectangle($im,$qx,$qy,$qx+$size,$qy+$size,certificate_color($im,'#FFFFFF'));for($r=0;$r<$n;$r++)for($c=0;$c<$n;$c++)if($qr->isDark($r,$c))imagefilledrectangle($im,$qx+(($c+$q)*$m),$qy+(($r+$q)*$m),$qx+(($c+$q+1)*$m)-1,$qy+(($r+$q+1)*$m)-1,certificate_color($im,'#000000'));certificate_draw_text($im,'VERIFY WITH CONFIDENCE',$cardX+18,$cardY+48,18,'#1F4B45',$bold);certificate_draw_text($im,'Scan to confirm this certificate',$cardX+18,$cardY+82,15,'#333333',$font);certificate_draw_text($im,'against JUVA Oil live records.',$cardX+18,$cardY+108,15,'#333333',$font);certificate_draw_text($im,'AUTHENTIC  |  TRACEABLE  |  SECURE',$cardX+18,$cardY+157,13,'#1F4B45',$bold);certificate_draw_text($im,'SCAN TO VERIFY',$qx+(int)($size/2),$cardY+$cardH-12,13,'#1F4B45',$bold,'center');}
    if($y+52>1405)throw new RuntimeException('Hook certificate content exceeds the one-page landscape layout.');
    $jpg=tempnam(sys_get_temp_dir(),'juva-hook-');if($jpg===false)throw new RuntimeException('Unable to create Hook render workspace.');imagejpeg($im,$jpg,94);imagedestroy($im);certificate_create_jpeg_pdf_landscape($path,$jpg);
}
