import { useEffect, useMemo, useState, type ReactNode } from "react";
import { CopyPlus, ExternalLink, FileBadge, Mail, Pencil, QrCode, Search, X } from "lucide-react";

type RoleLike={slug:string;permissions:string[]};type UserLike={role:RoleLike};type ApiResponse<T>={data:T|null;error:string|null;validation?:any};type ApiRequest=<T>(path:string,options?:RequestInit,csrf?:string)=>Promise<ApiResponse<T>>;type Row=Record<string,any>;
type Props={csrf:string;user:UserLike;request:ApiRequest;onOpenInspection?:(id:number)=>void};
const can=(u:UserLike,p:string)=>u.role.permissions.includes("*")||u.role.permissions.includes(p);
function tone(s:string){s=s.toLowerCase();if(["valid","issued","approved","active"].includes(s))return"valid";if(["submitted","pending"].includes(s))return"warning";if(["expired","revoked"].includes(s))return"danger";return"neutral"}
function StatusBadge({status}:{status:string}){return <span className={`status-badge status-${tone(status)}`}>{status}</span>}
function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="panel"><header className="panel-header"><h2>{title}</h2>{action}</header>{children}</section>}
export function EnhancedCertificateRegisterPage({csrf,user,request,onOpenInspection}:Props){
 const [certs,setCerts]=useState<Row[]>([]),[inspections,setInspections]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[detail,setDetail]=useState<any>(null),[notifications,setNotifications]=useState<Row[]>([]);const [message,setMessage]=useState(""),[error,setError]=useState("");
 const [q,setQ]=useState(""),[debouncedQ,setDebouncedQ]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[pages,setPages]=useState(1),[total,setTotal]=useState(0);
 const canIssue=can(user,"certificates.issue")||["super-admin","operations-admin"].includes(user.role.slug),canRenew=can(user,"inspections.create")||can(user,"inspections.edit");
 useEffect(()=>{const timer=window.setTimeout(()=>{setDebouncedQ(q);setPage(1)},350);return()=>window.clearTimeout(timer)},[q]);
 async function load(){const params=new URLSearchParams({page:String(page),per_page:"25"});if(debouncedQ)params.set("q",debouncedQ);if(status)params.set("status",status);const [c,i]=await Promise.all([request<any>(`/certificates/index.php?${params}`),request<any>("/inspections/index.php")]);if(c.data){setCerts(c.data.certificates||[]);setPages(c.data.pagination?.pages||1);setTotal(c.data.pagination?.total||0);if(selected&&!c.data.certificates.some((x:Row)=>String(x.id)===String(selected.id)))setSelected(null)}if(i.data)setInspections((i.data.inspections||[]).filter((x:Row)=>["approved","issued"].includes(String(x.status))));if(c.error)setError(c.error)}
 useEffect(()=>{void load()},[debouncedQ,status,page]);
 async function openDetail(cert:Row){setSelected(cert);const [r,n]=await Promise.all([request<any>(`/certificates/detail.php?id=${cert.id}`),request<any>(`/certificates/notifications.php?certificate_id=${cert.id}`)]);if(r.data)setDetail(r.data);else setError(r.error||"Unable to load certificate details.");setNotifications(n.data?.notifications||[])}
 async function openPdf(cert:Row){setError("");const url=String(cert.pdf_url||cert.pdf_path||"");if(!url){setError("PDF not available. Create a revision or view the source inspection to repair this certificate.");return}const win=window.open("","_blank");try{const response=await fetch(url,{credentials:"include"});if(!response.ok)throw new Error("PDF not available");const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);if(win)win.location.href=objectUrl;else window.open(objectUrl,"_blank")}catch{if(win)win.close();setError("PDF not available. Use Create revision to regenerate it, or view the source inspection.")}}
 async function repair(cert:Row){if(!window.confirm(`Mark ${cert.certificate_number} invalid and reopen its inspection for repair?`))return;const r=await request<any>("/certificates/repair.php",{method:"POST",body:JSON.stringify({id:cert.id,reason:"Incomplete issuance requires evidence repair."})},csrf);if(r.error){setError(r.error);return}setMessage(r.data?.message||"Certificate opened for repair.");onOpenInspection?.(Number(r.data?.inspection_id||cert.inspection_id));await load()}
 async function generate(id:number){setError("");const ready=await request<any>(`/certificates/readiness.php?inspection_id=${id}`);if(ready.data&&!ready.data.ready){const labels=[...(ready.data.missing_fields||[]).map((x:Row)=>x.label),...(ready.data.missing_sections||[]).map((x:Row)=>x.label)];setError(`Certificate is not ready. Complete: ${labels.join(", ")||Object.values(ready.data.validation_errors||{}).join(" ")}`);return}const r=await request<Row>("/certificates/generate.php",{method:"POST",body:JSON.stringify({inspection_id:id})},csrf);if(r.error){setError(r.error);return}setMessage(r.data?.unchanged?`Opening existing certificate: ${r.data.certificate_number}`:`Certificate issued: ${r.data?.certificate_number}`);if(r.data?.pdf_url)await openPdf({...r.data,pdf_path:r.data.pdf_url});await load()}
 async function renew(cert:Row){if(!window.confirm(`Create a renewal draft from ${cert.certificate_number}?`))return;const r=await request<any>("/inspections/clone.php",{method:"POST",body:JSON.stringify({inspection_id:Number(cert.inspection_id)})},csrf);if(r.error||!r.data?.inspection){setError(r.error||"Unable to clone certificate.");return}setMessage(`Draft cloned successfully from certificate ${cert.certificate_number}. Review the details, update dates and inspection results, then submit.`);onOpenInspection?.(Number(r.data.inspection.id))}
 async function revoke(id:number){const reason=window.prompt("Revocation reason");if(!reason)return;const r=await request("/certificates/revoke.php",{method:"POST",body:JSON.stringify({id,reason})},csrf);if(r.error){setError(r.error);return}setMessage("Certificate revoked.");await load()}
 async function createRevision(cert:Row){const reason=window.prompt("Reason for creating a new certificate revision");if(!reason)return;const r=await request<Row>("/certificates/create-revision.php",{method:"POST",body:JSON.stringify({id:cert.id,reason})},csrf);if(r.error){setError(r.error);return}setMessage(`Revision v${r.data?.revision} created for ${cert.certificate_number}.`);await load()}
 async function resend(notificationId:number){const r=await request<any>("/certificates/resend-notification.php",{method:"POST",body:JSON.stringify({notification_id:notificationId})},csrf);if(r.error){setError(r.error);return}setMessage(r.data?.sent?"Certificate email sent.":`Email remains queued: ${r.data?.error||"delivery failed"}`);if(selected)await openDetail(selected)}
 function primaryActions(cert:Row){return <div className="archive-primary-actions" onClick={e=>e.stopPropagation()}><button className="compact-action" onClick={()=>void openPdf(cert)}><FileBadge size={14}/><span className="action-label">Open</span></button><a className="compact-action" href={cert.verification_url} target="_blank" rel="noreferrer"><ExternalLink size={14}/><span className="action-label">Verify</span></a></div>}
 function actions(cert:Row){return <div className="certificate-drawer-actions"><button className="secondary-button" onClick={()=>void openPdf(cert)}><FileBadge size={14}/>Open Certificate</button><a className="secondary-button" href={cert.verification_url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Verification page</a>{(cert.qr_url||cert.barcode_path)&&<a className="secondary-button" href={cert.qr_url||cert.barcode_path} target="_blank" rel="noreferrer"><QrCode size={14}/>Open QR</a>}<button className="secondary-button" onClick={()=>onOpenInspection?.(Number(cert.inspection_id))}><Pencil size={14}/>View inspection</button>{canRenew&&<button className="secondary-button" onClick={()=>void renew(cert)}><CopyPlus size={14}/>Clone / Renew</button>}{canIssue&&<button className="secondary-button" onClick={()=>void createRevision(cert)}>Create revision</button>}{canIssue&&<button className="secondary-button" onClick={()=>void repair(cert)}>Repair issuance</button>}{canIssue&&String(cert.status)!=="revoked"&&<button className="danger-button" onClick={()=>void revoke(Number(cert.id))}>Revoke</button>}</div>} const active=useMemo(()=>certs.filter(c=>String(c.status)==="valid").length,[certs]);
 return <><div className="page-heading"><div><p className="eyebrow">CERTIFICATE GENERATION</p><h1>Certificates</h1><span>{total} certificate(s) found � {active} valid on this page</span></div></div>{error&&<div className="inline-alert form-error"><span>{error}</span><button onClick={()=>setError("")}><X size={16}/></button></div>}{message&&<div className="inline-alert form-success">{message}</div>}
 <Panel title="Approved inspections ready for certificate"><div className="table-scroll"><table><thead><tr><th>Reference</th><th>Client</th><th>Equipment</th><th>Type</th><th>Status</th><th/></tr></thead><tbody>{inspections.map(row=><tr key={row.id} className="clickable-row" onClick={()=>onOpenInspection?.(Number(row.id))}><td className="mono">{row.reference}</td><td>{row.client_name}</td><td>{row.asset_code} - {row.equipment_name}</td><td>{row.category_name}</td><td><StatusBadge status={row.status}/></td><td onClick={e=>e.stopPropagation()}>{canIssue&&<button className="primary-button" onClick={()=>{const cert=certs.find(c=>Number(c.inspection_id)===Number(row.id));if(row.status==="issued"&&cert)void openPdf(cert);else void generate(Number(row.id))}}>{row.status==="issued"?"Open Certificate":"Check & issue"}</button>}</td></tr>)}</tbody></table></div></Panel>
 <Panel title="Issued certificate archive" action={<button className="secondary-button" onClick={()=>{setQ("");setStatus("");setPage(1)}}>Reset filters</button>}><div className="archive-filters"><label><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Certificate, client, CCU, equipment, serial or inspector"/></label><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">All statuses</option><option value="valid">Valid</option><option value="expired">Expired</option><option value="revoked">Revoked</option></select></div><div className="table-scroll archive-table-wrap"><table className="archive-table"><thead><tr><th>Certificate</th><th className="archive-secondary">Rev</th><th>Client</th><th>Equipment</th><th>Category</th><th>Issued</th><th>Expires</th><th>Status</th><th>Actions</th></tr></thead><tbody>{certs.map(cert=><tr key={cert.id} className={`clickable-row ${selected?.id===cert.id?"selected-row":""}`} onClick={()=>void openDetail(cert)}><td className="mono">{cert.certificate_number}</td><td className="archive-secondary">v{cert.revision}</td><td title={cert.client_name}>{cert.client_name}</td><td>{cert.asset_code} - {cert.equipment_name}</td><td>{cert.category_name}</td><td>{cert.issued_at}</td><td>{cert.expires_at}</td><td><StatusBadge status={cert.status}/></td><td>{primaryActions(cert)}</td></tr>)}</tbody></table><div className="certificate-card-list">{certs.map(cert=><article key={`card-${cert.id}`} className="certificate-card" onClick={()=>void openDetail(cert)}><header><strong>{cert.certificate_number}</strong><StatusBadge status={cert.status}/></header><dl><div><dt>Client</dt><dd>{cert.client_name}</dd></div><div><dt>Category</dt><dd>{cert.category_name}</dd></div><div><dt>Equipment</dt><dd>{cert.asset_code} - {cert.equipment_name}</dd></div><div><dt>Expires</dt><dd>{cert.expires_at}</dd></div></dl><footer onClick={e=>e.stopPropagation()}>{primaryActions(cert)}</footer></article>)}</div>{!certs.length&&<div className="empty-state"><Search size={32}/><strong>No matching certificates</strong><span>Change the search term or reset the filters.</span></div>}</div><div className="pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></Panel>
 {detail?.certificate&&selected&&<div className="drawer-backdrop" onClick={()=>{setSelected(null);setDetail(null)}}><aside className="record-drawer" onClick={e=>e.stopPropagation()}><header><div><span className="eyebrow">CERTIFICATE RECORD</span><h2>{detail.certificate.certificate_number}</h2><p>{detail.certificate.client_name} � {detail.certificate.asset_code} - {detail.certificate.equipment_name}</p></div><button className="icon-button" onClick={()=>{setSelected(null);setDetail(null)}} title="Close"><X size={20}/></button></header><dl className="record-detail-list"><div><dt>Status</dt><dd><StatusBadge status={detail.certificate.status}/></dd></div><div><dt>Revision</dt><dd>v{detail.certificate.revision}</dd></div><div><dt>Inspection</dt><dd className="mono">{detail.certificate.inspection_reference}</dd></div><div><dt>Issued</dt><dd>{detail.certificate.issued_at}</dd></div><div><dt>Expires</dt><dd>{detail.certificate.expires_at}</dd></div><div><dt>Inspector</dt><dd>{detail.certificate.inspector_name}</dd></div></dl>{actions(detail.certificate)}<h3>Notification delivery</h3><div className="notification-list">{notifications.length===0&&<p>No notification has been queued for this certificate.</p>}{notifications.map(n=><div className="notification-row" key={n.id}><span>{n.recipient_email}</span><StatusBadge status={n.status}/><small>Revision {n.revision} � Attempts {n.attempts}/{n.max_attempts}{n.last_error?` � ${n.last_error}`:""}</small>{canIssue&&n.status!=="sent"&&<button className="secondary-button" onClick={()=>void resend(Number(n.id))}><Mail size={14}/>Resend</button>}</div>)}</div><h3>Revision history</h3><div className="revision-list">{(detail.revisions||[]).map((r:Row)=><div key={r.revision}><strong>v{r.revision}</strong><span>{r.created_at}</span><code>{String(r.pdf_hash).slice(0,16)}�</code></div>)}</div></aside></div>} </>}
